name: ❌ Do not open new issues on this repo
description:  Use the xojs/xo repo for new issues
body:
  - type: markdown
    attributes:
      value: |
        # Use the [XO issue tracker](https://github.com/xojs/xo/issues) instead of this one.
  - type: input
    id: ignored-but-required
    attributes:
      label: ❌
